
import { GoogleGenAI, Modality } from "@google/genai";
import { ImageFile } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateReziImage = async (
  childImage: ImageFile,
  currentImage: ImageFile,
  userPrompt: string
): Promise<ImageFile> => {
  try {
    const model = 'gemini-2.5-flash-image';
    
    const structuredPrompt = `Create a single, seamless, photorealistic image where the adult from the second photo is warmly hugging or interacting with the child from the first photo.
    Merge them into a new, cohesive scene that feels nostalgic and emotional. 
    User's specific request: "${userPrompt}"`;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: childImage.base64,
              mimeType: childImage.mimeType,
            },
          },
          {
            inlineData: {
              data: currentImage.base64,
              mimeType: currentImage.mimeType,
            },
          },
          {
            text: structuredPrompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return {
          base64: part.inlineData.data,
          mimeType: part.inlineData.mimeType,
        };
      }
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};
